config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "interfaces#index"

  resources :interfaces do
    get "send_message", on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/interface.rb
require 'rest-client'

class Interface < ApplicationRecord

  def self.request(params)
    # params = { "question" => "Can I learn the contact information of Çukurova University?", "language" => "EN" }
    question = params["question"]
    language = params["language"].downcase
    url = "http://127.0.0.1:5000/ask"

    # response = RestClient.get(url, {params: {'question': question, 'language': language}})
    # response.body

    # puts response.body, response.code, response.message, response.headers.inspect
    "Return Answer"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/interfaces_controller.rb
class InterfacesController < ApplicationController

  def index

  end

  def send_message
    render json: {answer: Interface.request(params)}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interfaces_helper.rb
module InterfacesHelper
end

app/views/interfaces/index.html.erb
<div class="header">
  <div class="chat-field" id="all-chat">



  </div>
</div>

<div class="footer">
  <div class="message-input">
    <%= form_with url: send_message_interfaces_path, id: "question-form", data: {controller: "interface", action: 'submit->interface#sendQuestion'} do |f|%>
      <%= f.select :language, ["TR", "EN"], {}, class: "form-input"%>
      <%= f.text_field :question, class: "form-input", placeholder: "Okulumuz ile ilgili soru sor"%>
      <%= f.submit "Gönder" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CuChatUi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>